# This file was generated by GoReleaser. DO NOT EDIT.
cask "kairo" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "312b0ddb12193de0ec5961cef2481f7707a1056ccb739cb9bdd5c028eddfbbfb"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b7b187633f2c1fab49c92b4ee8978641551d3929ec5d6e2bd6c30d2025f9202f"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac8d03048e610ebcd7d73254e40f6640c404b64dd0fc51ebe4ab493e4e9ac24b"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2bb54ef5c2f48f7fdc9462bab7a4b8122ac4d61e24b23dbfbfa90f6a304b1be7"
      url "https://github.com/programmersd21/kairo/releases/download/#{version}/kairo_linux_arm64.tar.gz"
    end
  end

  name "kairo"
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kairo"

  # No zap stanza required

end
