# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kairo < Formula
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"
  version "1.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/programmersd21/kairo/releases/download/1.2.3/kairo_darwin_x86_64.tar.gz"
      sha256 "4b647a8799f930ed91e56fa2a05c8a225bcd34ee3a9a6e69279268891bf801f4"

      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/programmersd21/kairo/releases/download/1.2.3/kairo_darwin_arm64.tar.gz"
      sha256 "dadabdbd5c37ee1d2487d2c8459cf05d9acdcb3dd10aadf2fe80e2dc1ab4e36d"

      define_method(:install) do
        bin.install "kairo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.2.3/kairo_linux_x86_64.tar.gz"
      sha256 "054e66b24d733d4cbaa132c56aa5fc7def7bacbf9ed0a5f41199604514ccea98"
      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.2.3/kairo_linux_arm64.tar.gz"
      sha256 "2877fa754f2afee2f74bfc5eae5e71503f2d1573e85468d3575c4f2f9dd9537f"
      define_method(:install) do
        bin.install "kairo"
      end
    end
  end
end
