# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kairo < Formula
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"
  version "1.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.4/kairo_darwin_x86_64.tar.gz"
      sha256 "7040110906afc0999e9bb448702982d870bb856b7732cdbe439a003f24803f22"

      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.4/kairo_darwin_arm64.tar.gz"
      sha256 "db8de2b5e58bf60cf97e468c0e773289e84891701c9e94b079d00cc0a6a291bf"

      define_method(:install) do
        bin.install "kairo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.4/kairo_linux_x86_64.tar.gz"
      sha256 "d88ae70846aa9ec997e518d9ffd26a6c5690b74afda5c35fe665a382dd10b3fa"
      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.4/kairo_linux_arm64.tar.gz"
      sha256 "0987f6c0f49ea601daa42235c6a81990a86223bc7bad3d5cbbc2eaaaa9be44be"
      define_method(:install) do
        bin.install "kairo"
      end
    end
  end

  test do
    system "#{bin}/kairo", "--version"
  end
end
