# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kairo < Formula
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.3/kairo_darwin_x86_64.tar.gz"
      sha256 "fc61378f740dafd3699b355ae4132d5a679cee50224fcca884c1dbc6cf3b4930"

      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.3/kairo_darwin_arm64.tar.gz"
      sha256 "f181f187de1e439cc4990225ad154951fd674a26505d04411644b4f191c62249"

      define_method(:install) do
        bin.install "kairo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.3/kairo_linux_x86_64.tar.gz"
      sha256 "60a1e7503fdf9a7e684524c622f74b9af7ec4c6126681fb0fc49b55065b91eb1"
      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.3/kairo_linux_arm64.tar.gz"
      sha256 "6f90e960b6c9cc7af4dfea6aa30a9c0e61e82c3817d37bdeff40da35bbaa932b"
      define_method(:install) do
        bin.install "kairo"
      end
    end
  end

  test do
    system "#{bin}/kairo", "--version"
  end
end
