# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kairo < Formula
  desc "Minimal, powerful task management"
  homepage "https://github.com/programmersd21/kairo"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.2/kairo_darwin_x86_64.tar.gz"
      sha256 "9abfa39632ef90022438a77a3b2dd231a17e5c85c86d05ef75fad339164e423b"

      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.2/kairo_darwin_arm64.tar.gz"
      sha256 "7b9490c826ea103ea6928215fe8e8271bfbd0bb585eafbc0c41c9b5214b4c8e6"

      define_method(:install) do
        bin.install "kairo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.2/kairo_linux_x86_64.tar.gz"
      sha256 "b7a4649cdf5b5fbee54560ab2620372e3c36ab0cc001169ed3d4c380f10dc7c6"
      define_method(:install) do
        bin.install "kairo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/kairo/releases/download/1.3.2/kairo_linux_arm64.tar.gz"
      sha256 "4fe69fb35431bdcdf815196996ddad32049135fd24c656d66c07613e8a95018c"
      define_method(:install) do
        bin.install "kairo"
      end
    end
  end

  test do
    system "#{bin}/kairo", "--version"
  end
end
